import csv
import hashlib
import os
import random
import re
from typing import Any
from typing import Union, List, Tuple, Dict

import numpy as np
import torch
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset

import cbct_artifact_reduction.config as cfg
import cbct_artifact_reduction.implantmaskcreator as imc
from cbct_artifact_reduction import lakefs_own
from cbct_artifact_reduction.dataprocessing import (
    min_max_normalize_common,
    remove_outliers,
    single_nifti_to_numpy,
)
from cbct_artifact_reduction.lakefs_own import CustomBoto3Client
from cbct_artifact_reduction.utils import lookup_num_in_datatable

import visdom
cfgg = {"server": "localhost", "port": 8823}
viz = visdom.Visdom('http://' + cfgg["server"], port = cfgg["port"])

def visualize(img):
    _min = img.min()
    _max = img.max()
    normalized_img = (img - _min)/ (_max - _min)
    return normalized_img


def clean_dict(data):
    """Extract single-element lists, tensor values, and convert NaN values to None.

    Args:
        data (dict): A dictionary with with single-element lists, tensor values, and NaN values.

    Returns:
        dict: A new cleaned dictionary.
    """
    cleaned_data = {}
    for key, value in data.items():
        # Extract single-element lists
        if isinstance(value, list) and len(value) == 1:
            value = value[0]

        # Extract tensor values and convert to Python types
        if isinstance(value, torch.Tensor):
            value = value.item()  # Extract single value from tensor

        # Convert NaN values to None
        if isinstance(value, tuple) and len(value) == 1:
            value = value[0]  # Extract from tuple
        if isinstance(value, float) and np.isnan(value):
            value = None  # Replace NaN with None

        cleaned_data[key] = value

    return cleaned_data


def replace_none_with_default(dictionary, default_value):
    """Recursively replaces None values in a dictionary with a default value.

    Args:
        dictionary (dict): A dictionary with None values to be replaced.
        default_value (Any): The value to replace None with.

    Returns:
        dict: A new dictionary with replaced None values.
    """
    if isinstance(dictionary, dict):
        return {
            k: replace_none_with_default(v, default_value)
            for k, v in dictionary.items()
        }
    elif dictionary is None:
        return default_value
    return dictionary

def list_lakefs_files(
    lakefs_loader,
    prefix,
    extension,
) -> list[str]:

    s3_client = lakefs_loader.client

    # Extract bucket name from the client's endpoint configuration
    bucket = lakefs_loader.repo  # lakeFS repository name


    filenames = []
    continuation_token = None

    while True:
        kwargs = {
            "Bucket": bucket,
            "Prefix": prefix,
        }

        if continuation_token:
            kwargs["ContinuationToken"] = continuation_token

        response = s3_client.list_objects_v2(**kwargs)

        if "Contents" not in response:
            break

        for obj in response["Contents"]:
            key = obj["Key"]

            if extension is None or key.endswith(extension):
                filenames.append(key)

        if response.get("IsTruncated"):
            continuation_token = response["NextContinuationToken"]
        else:
            break

    return filenames


def get_filenames_from_csv(csv_path):
    filenames = []
    with open(csv_path, "r") as csv_file:
        csv_reader = csv.reader(csv_file)
        next(csv_reader)  # Skip the header row
        for row in csv_reader:
            filenames.append(row[0].strip())

    return filenames


# TODO: Move this function to a separate file or module. Function is generated by ChatGPT.
def extract_number_before_underscore(input_string):
    # Match one or more digits (\d+) followed by an underscore (_)
    match = re.match(r"(\d+)_", input_string)
    if match:
        return int(match.group(1))  # Convert the matched number to an integer
    else:
        raise ValueError("Input string does not match the expected format.")


class InpaintingSliceDataset(Dataset):
    """A dataset containing slices of CBCT scans and binary masks to train a model for inpainting.

    The class uses a boto3client object to cache the data from LakeFS to the local filesystem when needed."""

    def __init__(
        self,
        lakefs_loader: CustomBoto3Client,
        filenames: Union[str, List[str]],
        slice_directory_path: str,
        random_masks: bool = True,
        augment_data: bool = True,
        log_transform: bool = False,
    ) -> None:
        """Initializes the dataset.

        Args:
            lakefs_loader (boto3client): The LakeFSLoader object used to load data from LakeFS.
            filenames list[str]: The list of filenames to load. Can be a path to a csv file or a list of filenames.
            relative_slice_directory_path (str): The relative path to the remote/local directory containing the slices.
            random_masks (bool): Whether to generate random masks or use the random generated masks with the hash of the file name.
            augment_data (bool): Whether to augment the data with flips.
            log_transform (bool): Whether to apply scanner specific log transformation.
        """

        super().__init__()
        self.lakefs_loader = lakefs_loader
        self.filenames = filenames
        self.relative_slice_directory_path = slice_directory_path
        self.random_masks = random_masks
        self.augment_data = augment_data
        self.log_transform = log_transform

        self.data_extension = ".nii.gz"
        self.dataset = self.prepare_dataset()
        # TODO: Don't hardcode the resolution
        self.mask_creator = imc.ImplantMaskCreator((256, 256))

        print("Dataset Information:")
        print(f"- Dataset length: {len(self.dataset)}")
        print(f"- Random masks: {self.random_masks}")
        print(f"- Augment data: {self.augment_data}")
        print(f"- Log transform: {self.log_transform}")

    def prepare_dataset(self) -> list[dict[str, Any]]:
        """Create a list of data points, each containing the path to the slice and information about the data to which the slice belongs.

        Returns:
            list[dict]: A list of dictionaries containing slice_path and data_info.
        """
        dataset = []

        if isinstance(self.filenames, str):
            client = lakefs_own.CustomBoto3Client(cfg.LAKEFS_DATA_REPOSITORY)

            #files = list_lakefs_files(client,prefix="INR_diffusion_paired",extension=".nii.gz")

            self.filenames = get_filenames_from_csv(self.filenames)
            self.filenames = [f for f in self.filenames if "gt" not in f]
            #self.filenames = [f for f in self.filenames if "sirt" not in f]

        for filename in self.filenames:
            slice_filename = filename.strip()

            slice_path = os.path.join(
                self.relative_slice_directory_path, slice_filename
            )
            # TODO: Don't hardcode the id length. Specify it somewhere or use regex or some function.
            id = extract_number_before_underscore(slice_filename)
            data_info = lookup_num_in_datatable(id)
            if data_info:
                data_info.update({"filename": slice_filename})

            datapoint = {"slice_path": slice_path, "data_info": data_info}

            dataset.append(datapoint)

        return dataset

    def get_mask(self, local_slice_path: str) -> np.ndarray:

        mask_np_array = self.mask_creator.generate_mask()

        return mask_np_array


    def __getitem__(
            self, idx: int
        ) -> Union[Tuple[np.ndarray, np.ndarray], Tuple[np.ndarray, np.ndarray, Dict]]:
        """Downloads the idx-th slice and from LakeFS and creates a mask for it.
        Optionally, it can also return the data_info, if set in the class constructor.
        Uses cache if the files are already downloaded.

        Args:
            idx (int): The index of the slice to return.

        Returns:
            dict[str, Any]: A dictionary containing the following keys:
                - slice (np.ndarray): containing the slice.
                - mask (np.ndarray): containing the mask.
                - info (optional): dict containing the data_info.
        """

        try:
            assert 0 <= idx < self.__len__(), f"Index {idx} out of bounds"
        except AssertionError:
            print(f"Index {idx} out of bounds. Returning other item.")
            idx = len(self.dataset) // 2

        datapoint = self.dataset[idx]

        item_path = datapoint["slice_path"]
        item_gt_path = item_path.replace('_inr_', '_gt_')
        #item_gt_path = item_path.replace('_inr_reco_view2.nii.gz', '_gt_reco_view2.nii.gz')
        #item_sirt_path = item_path.replace('_inr_reco.nii.gz', '_sirt_reco.nii.gz')
        item_info = datapoint["data_info"]

        # Download the slice from lakeFS. If it is not found this will be None.
        local_slice_path = self.lakefs_loader.get_file(item_path)
        local_slice_path_gt = self.lakefs_loader.get_file(item_gt_path)
        #local_slice_path_sirt = self.lakefs_loader.get_file(item_sirt_path)


        if local_slice_path is None:
            print(f"File {item_path} not found on lakeFS. Deleting item from dataset.")
            breakpoint()
            self.dataset.pop(idx)
            if idx >= len(self.dataset):
                idx = len(self.dataset) // 2
            return self.__getitem__(idx)

        if local_slice_path_gt is None:
            print(f"File {item_path} not found on lakeFS. Deleting item from dataset.")
            breakpoint()
            self.dataset.pop(idx)
            if idx >= len(self.dataset):
                idx = len(self.dataset) // 2
            return self.__getitem__(idx)

        # if local_slice_path_sirt is None:
        #     print(f"File {item_path} not found on lakeFS. Deleting item from dataset.")
        #     breakpoint()
        #     self.dataset.pop(idx)
        #     if idx >= len(self.dataset):
        #         idx = len(self.dataset) // 2
        #     return self.__getitem__(idx)


        slice_np_array = single_nifti_to_numpy(local_slice_path)
        slice_np_array_gt = single_nifti_to_numpy(local_slice_path_gt)
        #slice_np_array_sirt = single_nifti_to_numpy(local_slice_path_sirt)
        mask_np_array = self.get_mask(local_slice_path)

        if self.augment_data:
            if random.random() < 0.5:
                # Data augmentation. Randomly flip the image and mask horizontally.
                slice_np_array = slice_np_array[..., :, ::-1].copy()
                slice_np_array_gt = slice_np_array_gt[..., :, ::-1].copy()
                #slice_np_array_sirt = slice_np_array_sirt[..., :, ::-1].copy()

                #mask_np_array = mask_np_array[..., :, ::-1].copy()

        processed_slice_np_array = self.dataprocessing(slice_np_array, item_info)
        processed_slice_np_array_gt = self.dataprocessing(slice_np_array_gt, item_info)
        #processed_slice_np_array_sirt = self.dataprocessing(slice_np_array_sirt, item_info)


        breakpoint()

        #if item_path ...:
        # mask = np.zeros_like(processed_slice_np_array)
        # x = 128 - (45)
        # y = 128
        # r = 40
        # Y, X = np.ogrid[:256, :256]
        # dist_from_center = np.sqrt((X - x) ** 2 + (Y - y) ** 2)
        # _mask = dist_from_center <= r
        # mask[_mask==0]=1


        item = {
            "slice": processed_slice_np_array[np.newaxis, ...].astype(np.float32),
            "slice_gt": processed_slice_np_array_gt[np.newaxis, ...].astype(np.float32),
            #"slice_sirt": processed_slice_np_array_sirt[np.newaxis, ...].astype(np.float32),
            #"mask": mask_np_array[np.newaxis, ...].astype(np.float32),
        }


        return item

    def dataprocessing(
        self,
        np_array: np.ndarray,
        item_info: dict = {},
    ) -> np.ndarray:
        """Preprocesses the numpy array by normalizing it and removing outliers.
        Additionally, apply scanner specific preprocessing if log_transform is True.

        Args:
            nparray (np.ndarray): The numpy array to preprocess.
            item_info (dict, optional): The item info dictionary.
            log_transform (bool, optional): Whether to apply scanner specific preprocessing.
        Returns:
            np.ndarray: The preprocessed numpy array.
        """

        #np_array = remove_outliers(np_array)

        normalized = min_max_normalize_common(np_array)
        return normalized

    def __len__(self) -> int:
        return len(self.dataset)


if __name__ == "__main__":
    client = lakefs_own.CustomBoto3Client(f"{cfg.LAKEFS_DATA_REPOSITORY}")
    inpaintingSliceDataset = InpaintingSliceDataset(
        client,
        os.path.join(cfg.ROOT_DIR, ""),
        "reco_slices_256",
        random_masks=False,
    )

    #dataloader = DataLoader(inpaintingSliceDataset, batch_size=1, shuffle=True)

    #data = iter(dataloader)
    #print(next(data))
