# Parameters to setup CT simulation.

# dataset
numTrain: 499
numVal: 1

# System configuration
DSD: 1500.0 #700 #602.791  # Distance Source Detector      (mm)
DSO: 700.0 #700 #332.193  # Distance Source Origin        (mm)

# Detector parameters
nDetector: # Number of pixels              (px)
- 512 #250 #250 #256 #250 #840
- 512 #180 #230 wo outpainting #800 #800 # change this for outpainting! 600 #256 #600 #732 
dDetector: # Size of each pixel            (mm)
- 1.0 #0.127
- 1.0 #0.127

# Image parameters
nVoxel: # Number of voxels              (vx)
- 256 #668 #761 # 256 #761
- 256 #668 #761 # 256 #761
- 256 #668 #761 # 256 #761
dVoxel: # size of each voxel            (mm)
- 1.0 #0.15 #0.075 #0.22 # 0.22 #0.075
- 1.0 #0.15 #0.075 #0.22 # 0.22 #0.075
- 1.0 #0.391 #0.15 #0.075 #0.22 # 0.22 #0.075

# Offsets
offOrigin: # Offset of image from origin   (mm)
- 0 #0 # x direction
- 0 #1 # y direction
- 0 #0.9692581524295071 # z direction
offDetector: # Offset of Detector (only in two direction)            (mm)
- 0 #-0.306990202886698 # u direction
- 0 #-1.13882937271764 # v direction

# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj          (vx/sample)

# Mode
mode: cone # X-ray source mode parallel/cone
filter: null

# Angles
totalAngle: 210.0 # Total angle  (degree)
startAngle: 0.0 # Start angle (degree)
randomAngle: False

# CT
convert: True
rescale_slope: 1.0
rescale_intercept: -1024
normalize: True

# Noise
noise: True
